### ISSUE TITLE
mypy thinks VERSION is required on FastSpeech2Config construction

### ISSUE THREAD

**Issue by joanise** [EveryVoiceTTS/EveryVoice#581]
### Bug description

With #565 merged, we now get a new mypy error, which seems to indicate VERSION has to be specified when we construct a FastSpeech2Config object.

I thought the VERSION field would be optional, but apparently mypy doesn't think so.

### How to reproduce the bug

```python
mypy everyvoice/tests/test_preprocessing.py
```

Also:
```
pre-commit run --all
```
triggers a bunch more similar errors.

### Error messages and logs

```
everyvoice/tests/test_preprocessing.py:497: error: Missing named argument "VERSION" for "FastSpeech2Config"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by joanise** [comment]
@SamuelLarkin can you take a look?

**Comment by SamuelLarkin** [comment]
fixed by:

- https://github.com/EveryVoiceTTS/EveryVoice/pull/583
- https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/95
- https://github.com/EveryVoiceTTS/HiFiGAN_iSTFT_lightning/pull/40
- https://github.com/EveryVoiceTTS/DeepForcedAligner/pull/29
- https://github.com/EveryVoiceTTS/EveryVoice/pull/582
